# Generated by Django 3.1.7 on 2021-04-05 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('decription', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('description2', models.TextField()),
                ('img2', models.ImageField(upload_to='pics')),
                ('employee', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=255)),
                ('decription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category_picture', models.ImageField(upload_to='category-pictures')),
            ],
        ),
        migrations.CreateModel(
            name='SliderPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name2', models.CharField(max_length=255)),
                ('name3', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('subtitle2', models.TextField()),
                ('subtitle3', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('img3', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Vaucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('text', models.TextField()),
                ('text2', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('sale', models.BooleanField(default=False)),
                ('gender', models.BooleanField(default=True)),
                ('description', models.TextField(default='')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
        ),
    ]
