# Generated by Django 3.1.7 on 2021-03-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sliderpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderpicture',
            name='name2',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sliderpicture',
            name='name3',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sliderpicture',
            name='subtitle2',
            field=models.TextField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sliderpicture',
            name='subtitle3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
