# Generated by Django 3.1.7 on 2021-03-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210331_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('text', models.TextField()),
            ],
        ),
    ]
