# Generated by Django 3.1.7 on 2021-04-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_productpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img2',
        ),
    ]
