# Generated by Django 3.1.7 on 2021-04-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210405_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='', upload_to='product-pictures'),
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.ImageField(default='', upload_to='product-pictures'),
        ),
    ]
