# Generated by Django 3.1.7 on 2021-03-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_incentives_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentives',
            name='title',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
