# Generated by Django 3.1.7 on 2021-04-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210405_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='product-pictures'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(upload_to='product-pictures'),
        ),
    ]
