# Generated by Django 3.1.7 on 2021-03-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_incentives_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incentives',
            new_name='Vaucher',
        ),
    ]
