# Generated by Django 3.1.7 on 2021-04-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210405_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='settings')),
                ('phone', models.CharField(default='', max_length=255)),
                ('center_address', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
