# Generated by Django 3.1.7 on 2021-04-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='representation',
            field=models.TextField(default=''),
        ),
    ]
