# Generated by Django 3.1.7 on 2021-03-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
