# Generated by Django 3.1.7 on 2021-03-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_address_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('decription', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('description2', models.TextField()),
                ('img2', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
