# Generated by Django 3.1.7 on 2021-03-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Employee',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='branch',
            field=models.CharField(default=9, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='customer',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='user',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
